routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Guest
	Route::group(['middleware' => 'guest:web-admin', 'guard' => 'web-admin'], function() {
		Route::get('login', 'AuthController@loginPage')->name('login.page');
		Route::post('login', 'AuthController@login')->name('login');
	});

	// Logged In
	Route::group(['middleware' => 'auth:web-admin', 'guard' => 'web-admin'], function() {
	    Route::post('logout', 'AuthController@logout')->name('logout');

    	Route::get('', 'DashboardController@index')->name('dashboard');
		
		// User
		Route::group(['namespace' => 'User', 'prefix' => 'users', 'as' => 'users.'], function() {
			Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
				// List
				Route::get('/', 'UserController@index')->name('index');
				Route::post('/', 'UserController@ajax')->name('ajax');
				
				Route::get('/new', 'UserController@edit')->name('create');
				Route::get('/{user}/edit', 'UserController@edit')->name('edit');
				Route::post('/store', 'UserController@update')->name('store');
				Route::post('/{user}/update', 'UserController@update')->name('update');
				Route::delete('/{user}/delete', 'UserController@delete')->name('delete');
				Route::get('/{user}/detail', 'UserController@detail')->name('detail');
			});
		});
		// Order
		Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
			Route::get('/', 'OrderController@index')->name('index');
			Route::post('/', 'OrderController@ajax')->name('ajax');
			Route::post('/export-excel', 'OrderController@exportExcel')->name('export-excel');
			Route::get('/{order}/detail', 'OrderController@detail')->name('detail');
			Route::get('/{order}/edit', 'OrderController@edit')->name('edit');
			Route::post('/{order}/update', 'OrderController@update')->name('update');
			Route::post('/{order}/cancel', 'OrderController@cancel')->name('cancel');
		});
		// Articles
		Route::group(['prefix' => 'article', 'as' => 'article.'], function() {
			Route::get('/', 'ArticleController@index')->name('index');
			Route::post('/', 'ArticleController@ajax')->name('ajax');
			Route::get('/new', 'ArticleController@edit')->name('create');
			Route::get('/{article}/edit', 'ArticleController@edit')->name('edit');
			Route::post('/store', 'ArticleController@update')->name('store');
			Route::post('/{article}/update', 'ArticleController@update')->name('update');
			Route::delete('/{article}/delete', 'ArticleController@delete')->name('delete');
		});
		// Comments
		Route::group(['prefix' => 'comment', 'as' => 'comment.'], function() {
			Route::get('/', 'CommentController@index')->name('index');
			Route::post('/', 'CommentController@ajax')->name('ajax');
			Route::get('/new', 'CommentController@edit')->name('create');
			Route::get('/{comment}/edit', 'CommentController@edit')->name('edit');
			Route::post('/store', 'CommentController@update')->name('store');
			Route::post('/{comment}/update', 'CommentController@update')->name('update');
			Route::delete('/{comment}/delete', 'CommentController@delete')->name('delete');
		});
		// Latest Promotion
		Route::group(['prefix' => 'latest-promotion', 'as' => 'latest-promotion.'], function() {
			Route::get('/', 'PromoController@index')->name('index');
			Route::post('/', 'PromoController@ajax')->name('ajax');
			Route::get('/new', 'PromoController@edit')->name('create');
			Route::get('/{promo}/edit', 'PromoController@edit')->name('edit');
			Route::post('/store', 'PromoController@update')->name('store');
			Route::post('/{promo}/update', 'PromoController@update')->name('update');
			Route::delete('/{promo}/delete', 'PromoController@delete')->name('delete');
		});
		// Config
		Route::group(['prefix' => 'config', 'as' => 'config.'], function() {
			Route::get('/', 'ConfigController@index')->name('index');
			Route::post('/', 'ConfigController@ajax')->name('ajax');
			Route::get('/new', 'ConfigController@edit')->name('create');
			Route::get('/{config}/edit', 'ConfigController@edit')->name('edit');
			Route::post('/store', 'ConfigController@update')->name('store');
			Route::post('/{config}/update', 'ConfigController@update')->name('update');
			Route::delete('/{config}/delete', 'ConfigController@delete')->name('delete');
		});
		// Passenger
		Route::group(['prefix' => 'passenger', 'as' => 'passenger.'], function() {
			Route::get('/', 'PassengerController@index')->name('index');
			Route::post('/', 'PassengerController@ajax')->name('ajax');
			Route::get('/new', 'PassengerController@edit')->name('create');
			Route::get('/{passenger}/edit', 'PassengerController@edit')->name('edit');
			Route::post('/store', 'PassengerController@update')->name('store');
			Route::post('/{passenger}/update', 'PassengerController@update')->name('update');
			Route::delete('/{passenger}/delete', 'PassengerController@delete')->name('delete');
		});
		// Preference
		Route::group(['namespace' => 'Preference', 'prefix' => 'preferences', 'as' => 'preferences.'], function() {
			// Faq
			Route::group(['prefix' => 'faq', 'as' => 'faq.'], function(){
				Route::get('/', 'FaqController@index')->name('index');
				Route::post('/list', 'FaqController@ajax')->name('ajax');
				Route::get('/new', 'FaqController@edit')->name('create');
				Route::post('/store', 'FaqController@update')->name('store');
				Route::get('/customize-urut', 'FaqController@customizeUrut')->name('customize-urut');
				Route::post('/update-urut', 'FaqController@updateUrut')->name('update-urut');
				Route::get('/{faq}/edit', 'FaqController@edit')->name('edit');
				Route::post('/{faq}/save', 'FaqController@update')->name('update');
				Route::delete('/{faq}/delete', 'FaqController@delete')->name('delete');
			});
		});
	});
});

Route::view('/batam-ferry-timing', 'batam-ferry-timing.index');
Route::get('/{any}', 'SpaController@index')->where('any', '.*');

app/Models/Config.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Config extends Model
{
    use SoftDeletes;
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'key', 'value'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];
    protected $dates = ['deleted_at'];
    
}

app/Http/Controllers/Admin/ConfigController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Helpers\Managers\ConfigManager;
use App\Models\Config as AppConfig;
use Yajra\Datatables\Datatables;
use DB;
use Exception;

class ConfigController extends Controller
{
    public function index(Request $request)
    {
        return view('admin.config.index');
    }

    public function edit(Request $request, AppConfig $config)
    {
        return view('admin.config.form')
            ->with('config', $config);
    }

    public function ajax(Request $request)
    {
    	$data = AppConfig::query();
    	return Datatables::of($data)
                ->addColumn('action', function ($model) {
                    $str = '<div class="btn-group btn-group-circle">';
                    $str .= '<a href='. route('admin.config.edit', ['user' => $model]) .' class="action"><span class="far fa-edit"></span></a>';
                    $str .= '<a data-url="'. route('admin.config.delete', ['user' => $model]) .'" class="action" data-toggle="modal" data-target="#modalConfirm" data-table-name="#table" data-message="Are you sure want to delete this Config? This may cause a system <b>ERROR</b> or <b>FAILURE</b> towards this app"><span class="far fa-trash-alt"></span></a>';
                    $str .= '</div>';
                    return $str;
                })
                ->escapeColumns([])
				->make(true);
    }

    public function update(Request $request, AppConfig $config)
    {
        $messageType = $config->id ? 'updated' : 'created';

        $validatedData = $request->validate([
            'key' => 'required',
            'value' => 'required',
        ]);

        try {
            DB::beginTransaction();
            $configManager = new ConfigManager;
            $updateConfig = $configManager->update($config, $request->all());
            DB::commit();
            return redirect()->route('admin.config.index')->with('success', 'Config successfully '.$messageType);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return redirect()->back()->with('error', $errorMessage);
        }
    }

    public function delete(Request $request, AppConfig $config)
    {
        try {
            DB::beginTransaction();
            $configManager = new ConfigManager($request->user());
            $updatedConfig = $configManager->delete($config);
            DB::commit();
            return response()->json(['message' => 'Config Deleted'], 200);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return response()->json(['message' => $errorMessage], 500);
        }
    }
}

resources/views/admin/config/form.blade.php
@extends('templates.admin.master')

@section('title')
    {{ $config->id ? 'Edit' : 'Create'}} Config @parent
@endsection
@section('groupName', 'Config')

@section('content')
@if (!$config->id)
{!! Form::open(['route' => 'admin.config.store', 'method' => 'post', 'class' => 'form-horizontal']) !!}
@else
{!! Form::model($config, ['route' => ['admin.config.update', $config], 'method' => 'post', 'class' => 'form-horizontal']) !!}
@endif
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ $config->id ? 'Edit' : 'Create' }} Config</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <label for="key" class="col-2 col-form-label">Key</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('key', old('key'), array('class' => 'form-control', 'id' => 'key', 'placeholder' => 'Key')) }}
                        @if($errors->has('key'))
                        <p class="status-text">{{ $errors->first('key') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="value" class="col-2 col-form-label">Value</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::text('value', old('value'), array('class' => 'form-control', 'id' => 'value', 'placeholder' => 'Value')) }}
                        </div>
                        @if($errors->has('value'))
                        <p class="status-text">{{ $errors->first('value') }}</p>
                        @endif
                        <a class="status-text text-dark-grey pointer my-2 d-inline-flex align-items-center" id="switch"><i class="now-ui-icons loader_refresh fs-2 mr-1"></i><span>Switch to CK Editor</span></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="text-center">
                <button type="submit" class="btn btn-round btn-info"><i class="fas fa-paper-plane"></i> Submit</button>
            </div>
        </div>
    </div>
{!! Form::close() !!}
@endsection

@push('pageRelatedJs')
<script src="{{ asset('/ckeditor/ckeditor.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
    var useCkeditor = false;
    var wrapper = $('#wrapper');
    var text = $('#switch span');

    $('#switch').on('click', function() {
        useCkeditor = !useCkeditor;
        
        if (useCkeditor) {
            let val = wrapper.find('#value').val();

            wrapper.html('<textarea class="form-control" id="value" name="value" style="visibility: hidden; display: none;"></textarea>');
            wrapper.find('#value').val(val);

            CKEDITOR.replace('value', {
                height: 500
            });

            text.html('Switch to Normal Input');
        } else {
            let val = CKEDITOR.instances.value.getData();
            
            wrapper.html('<input class="form-control" id="value" placeholder="Value" name="value" type="text">');

            wrapper.find('#value').val(val);
            text.html('Switch to CK Editor');
        }
    });
});
</script>
@endpush

resources/views/admin/config/index.blade.php
@extends('templates.admin.master')
@extends('templates.datatables.datatables')

@section('title')
    Config List @parent
@endsection

@section('groupName', 'Config')

@section('content')
@include('templates.modal.modal-confirm')
<div class="card card-chart">
    <div class="card-header">
        <h4 class="card-title">Config List</h3>
        <div class="dropdown">
            <button type="button" class="btn btn-round btn-default dropdown-toggle btn-simple btn-icon no-caret" data-toggle="dropdown" aria-expanded="false">
                <i class="now-ui-icons loader_gear"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{{ route('admin.config.create') }}">Create new config</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered datatable dataTable" id="table" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Key</th>
                    <th>Value</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@endsection

@push('pageRelatedJs')
<script>
	$(document).ready(function(){
		var table = $('#table').DataTable(
		{
			processing: true,
			serverSide: true,
            responsive: true,
			ajax: {
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				url: '{!! route('admin.config.ajax') !!}',
				type: 'POST'
			},
			columns: [
                { data: 'id', name: 'id', className: 'text-center' },
                { data: 'key', name: 'key', className: 'text-center' },
                { data: 'value', name: 'value', render: function (data, type, full, meta) {
                    console.log(data);
                    return `<div class="html-render-box">${data}</div>`;
                    }
                },
                { data: 'action', name: 'action', className: 'text-center', sortable: false, searchable: false },
			]
		});
        $(table.table().container()).removeClass('form-inline');
	});
</script>
@endpush