routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Guest
	Route::group(['middleware' => 'guest:web-admin', 'guard' => 'web-admin'], function() {
		Route::get('login', 'AuthController@loginPage')->name('login.page');
		Route::post('login', 'AuthController@login')->name('login');
	});

	// Logged In
	Route::group(['middleware' => 'auth:web-admin', 'guard' => 'web-admin'], function() {
	    Route::post('logout', 'AuthController@logout')->name('logout');

    	Route::get('', 'DashboardController@index')->name('dashboard');
		
		// User
		Route::group(['namespace' => 'User', 'prefix' => 'users', 'as' => 'users.'], function() {
			Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
				// List
				Route::get('/', 'UserController@index')->name('index');
				Route::post('/', 'UserController@ajax')->name('ajax');
				
				Route::get('/new', 'UserController@edit')->name('create');
				Route::get('/{user}/edit', 'UserController@edit')->name('edit');
				Route::post('/store', 'UserController@update')->name('store');
				Route::post('/{user}/update', 'UserController@update')->name('update');
				Route::delete('/{user}/delete', 'UserController@delete')->name('delete');
				Route::get('/{user}/detail', 'UserController@detail')->name('detail');
			});
		});
		// Order
		Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
			Route::get('/', 'OrderController@index')->name('index');
			Route::post('/', 'OrderController@ajax')->name('ajax');
			Route::post('/export-excel', 'OrderController@exportExcel')->name('export-excel');
			Route::get('/{order}/detail', 'OrderController@detail')->name('detail');
			Route::get('/{order}/edit', 'OrderController@edit')->name('edit');
			Route::post('/{order}/update', 'OrderController@update')->name('update');
			Route::post('/{order}/cancel', 'OrderController@cancel')->name('cancel');
		});
		// Articles
		Route::group(['prefix' => 'article', 'as' => 'article.'], function() {
			Route::get('/', 'ArticleController@index')->name('index');
			Route::post('/', 'ArticleController@ajax')->name('ajax');
			Route::get('/new', 'ArticleController@edit')->name('create');
			Route::get('/{article}/edit', 'ArticleController@edit')->name('edit');
			Route::post('/store', 'ArticleController@update')->name('store');
			Route::post('/{article}/update', 'ArticleController@update')->name('update');
			Route::delete('/{article}/delete', 'ArticleController@delete')->name('delete');
		});
		// Comments
		Route::group(['prefix' => 'comment', 'as' => 'comment.'], function() {
			Route::get('/', 'CommentController@index')->name('index');
			Route::post('/', 'CommentController@ajax')->name('ajax');
			Route::get('/new', 'CommentController@edit')->name('create');
			Route::get('/{comment}/edit', 'CommentController@edit')->name('edit');
			Route::post('/store', 'CommentController@update')->name('store');
			Route::post('/{comment}/update', 'CommentController@update')->name('update');
			Route::delete('/{comment}/delete', 'CommentController@delete')->name('delete');
		});
		// Latest Promotion
		Route::group(['prefix' => 'latest-promotion', 'as' => 'latest-promotion.'], function() {
			Route::get('/', 'PromoController@index')->name('index');
			Route::post('/', 'PromoController@ajax')->name('ajax');
			Route::get('/new', 'PromoController@edit')->name('create');
			Route::get('/{promo}/edit', 'PromoController@edit')->name('edit');
			Route::post('/store', 'PromoController@update')->name('store');
			Route::post('/{promo}/update', 'PromoController@update')->name('update');
			Route::delete('/{promo}/delete', 'PromoController@delete')->name('delete');
		});
		// Config
		Route::group(['prefix' => 'config', 'as' => 'config.'], function() {
			Route::get('/', 'ConfigController@index')->name('index');
			Route::post('/', 'ConfigController@ajax')->name('ajax');
			Route::get('/new', 'ConfigController@edit')->name('create');
			Route::get('/{config}/edit', 'ConfigController@edit')->name('edit');
			Route::post('/store', 'ConfigController@update')->name('store');
			Route::post('/{config}/update', 'ConfigController@update')->name('update');
			Route::delete('/{config}/delete', 'ConfigController@delete')->name('delete');
		});
		// Passenger
		Route::group(['prefix' => 'passenger', 'as' => 'passenger.'], function() {
			Route::get('/', 'PassengerController@index')->name('index');
			Route::post('/', 'PassengerController@ajax')->name('ajax');
			Route::get('/new', 'PassengerController@edit')->name('create');
			Route::get('/{passenger}/edit', 'PassengerController@edit')->name('edit');
			Route::post('/store', 'PassengerController@update')->name('store');
			Route::post('/{passenger}/update', 'PassengerController@update')->name('update');
			Route::delete('/{passenger}/delete', 'PassengerController@delete')->name('delete');
		});
		// Preference
		Route::group(['namespace' => 'Preference', 'prefix' => 'preferences', 'as' => 'preferences.'], function() {
			// Faq
			Route::group(['prefix' => 'faq', 'as' => 'faq.'], function(){
				Route::get('/', 'FaqController@index')->name('index');
				Route::post('/list', 'FaqController@ajax')->name('ajax');
				Route::get('/new', 'FaqController@edit')->name('create');
				Route::post('/store', 'FaqController@update')->name('store');
				Route::get('/customize-urut', 'FaqController@customizeUrut')->name('customize-urut');
				Route::post('/update-urut', 'FaqController@updateUrut')->name('update-urut');
				Route::get('/{faq}/edit', 'FaqController@edit')->name('edit');
				Route::post('/{faq}/save', 'FaqController@update')->name('update');
				Route::delete('/{faq}/delete', 'FaqController@delete')->name('delete');
			});
		});
	});
});

Route::view('/batam-ferry-timing', 'batam-ferry-timing.index');
Route::get('/{any}', 'SpaController@index')->where('any', '.*');

app/Models/Passenger.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Enums\Gender;

class Passenger extends Model
{
    use SoftDeletes;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'passport_number', 'name', 'nationality', 'gender', 'dob', 'passport_expiry', 'issuing_country', 'passport_issue', 'type', 'ownable_type', 'ownable_id' 
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];

    protected $appends = [
        'gender_string',
        'dob_day',
        'dob_month',
        'dob_year',
        'passport_expiry_day',
        'passport_expiry_month',
        'passport_expiry_year',
        'passport_issue_day',
        'passport_issue_month',
        'passport_issue_year',
    ];

    protected $dates = [
        'dob', 'passport_expiry', 'passport_issue', 'deleted_at',
    ];

    public function ownable()
    {
    	return $this->morphTo();
    }

    public function getGenderStringAttribute()
    {
        return Gender::getString($this->gender);
    }

    public function getDobDayAttribute()
    {
        return $this->dob ? $this->dob->format('d') : '';
    }

    public function getDobMonthAttribute()
    {
        return $this->dob ? $this->dob->format('m') : '';
    }

    public function getDobYearAttribute()
    {
        return $this->dob ? $this->dob->format('Y') : '';
    }

    public function getPassportExpiryDayAttribute()
    {
        return $this->passport_expiry ? $this->passport_expiry->format('d') : '';
    }

    public function getPassportExpiryMonthAttribute()
    {
        return $this->passport_expiry ? $this->passport_expiry->format('m') : '';
    }

    public function getPassportExpiryYearAttribute()
    {
        return $this->passport_expiry ? $this->passport_expiry->format('Y') : '';
    }

    public function getPassportIssueDayAttribute()
    {
        return $this->passport_issue ? $this->passport_issue->format('d') : '';
    }

    public function getPassportIssueMonthAttribute()
    {
        return $this->passport_issue ? $this->passport_issue->format('m') : '';
    }

    public function getPassportIssueYearAttribute()
    {
        return $this->passport_issue ? $this->passport_issue->format('Y') : '';
    }
}

app/Http/Controllers/Admin/PassengerController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Helpers\Managers\PassengerManager;
use App\Enums\Gender;
use App\Enums\PassengerType;
use App\Models\Passenger;
use Yajra\Datatables\Datatables;
use DB;
use Exception;
use File;
use Illuminate\Support\Collection;

class PassengerController extends Controller
{
    public function index(Request $request)
    {
        return view('admin.passenger.index');
    }

    public function edit(Request $request, Passenger $passenger)
    {
        $countries = json_decode(File::get(storage_path('app/public/country.json')));
        $issuingCountries = json_decode(File::get(storage_path('app/public/issuing-country.json')));
        Collection::macro('toAssoc', function () {
            return $this->reduce(function ($assoc, $keyValuePair) {
                list($key, $value) = $keyValuePair;
                $assoc[$key] = $value;
                return $assoc;
            }, new static);
        });

        Collection::macro('mapToAssoc', function ($callback) {
            return $this->map($callback)->toAssoc();
        });

        $nationalities = collect($countries)->mapToAssoc(function ($country) {
            return [$country->value, $country->text];
        });

        $issuingNationalities = collect($issuingCountries)->mapToAssoc(function ($country) {
            return [$country->value, $country->text];
        });
        $genders = Gender::getArray();
        $types = PassengerType::getArray();
        return view('admin.passenger.form')
            ->with('nationalities', $nationalities)
            ->with('issuingNationalities', $issuingNationalities)
            ->with('genders', $genders)
            ->with('types', $types)
            ->with('passenger', $passenger);
    }

    public function ajax(Request $request)
    {
    	$data = Passenger::query();
    	return Datatables::of($data)
                ->addColumn('action', function ($model) {
                    $str = '<div class="btn-group btn-group-circle">';
                    $str .= '<a href='. route('admin.passenger.edit', ['user' => $model]) .' class="action"><span class="far fa-edit"></span></a>';
                    $str .= '<a data-url="'. route('admin.passenger.delete', ['user' => $model]) .'" class="action" data-toggle="modal" data-target="#modalConfirm" data-table-name="#table" data-message="Are you sure want to delete this data? This may cause a system <b>ERROR</b> or <b>FAILURE</b> towards this app"><span class="far fa-trash-alt"></span></a>';
                    $str .= '</div>';
                    return $str;
                })
                ->editColumn('dob', function ($model) {
                    return $model->dob->format('Y-m-d');
                })
                ->editColumn('passport_issue', function ($model) {
                    return $model->passport_issue->format('Y-m-d');
                })
                ->editColumn('passport_expiry', function ($model) {
                    return $model->passport_expiry->format('Y-m-d');
                })
                ->editColumn('gender', function ($model) {
                    return Gender::getString($model->gender);
                })
                ->editColumn('type', function ($model) {
                    return PassengerType::getString($model->type);
                })
                ->escapeColumns([])
                ->orderColumn('id', '-id $1')
				->make(true);
    }

    public function update(Request $request, Passenger $passenger)
    {
        $messageType = $passenger->id ? 'updated' : 'created';

        $validatedData = $request->validate([
            'passport_number' => 'required|unique:passengers,passport_number,'.$passenger->id.',id',
            'name' => 'required|string|alpha_spaces',
            'nationality' => 'required|string',
            'gender' => 'required|in:0,1,2',
            'dob' => 'required|date_format:Y-m-d',
            'passport_expiry' => 'required|date_format:Y-m-d',
            'issuing_country' => 'required|string',
            'passport_issue' => 'required|date_format:Y-m-d',
            'type' => 'required|in:0,1,2'
        ]);
        
        try {
            DB::beginTransaction();
            $passengerManager = new PassengerManager;
            $updatedPassenger = $passengerManager->update($passenger, $request->except('_token'));
            DB::commit();
            return redirect()->route('admin.passenger.index')->with('success', 'Passenger successfully '.$messageType);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return redirect()->back()->with('error', $errorMessage);
        }
    }

    public function delete(Request $request, Passenger $passenger)
    {
        try {
            DB::beginTransaction();
            $passengerManager = new PassengerManager($request->user());
            $updatedPassenger = $passengerManager->delete($passenger);
            DB::commit();
            return response()->json(['message' => 'Passenger Deleted'], 200);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return response()->json(['message' => $errorMessage], 500);
        }
    }
}

app/Http/Controllers/Api/V1/PassengerController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;
use App\Http\Controllers\Controller;
use App\Traits\ApiResponse;
use DB;
use Exception;
use App\Models\User;
use App\Models\Passenger;

class PassengerController extends Controller
{
    use ApiResponse;

    /**
     * Create a new AuthController instance.
     *
     * @return void
     */
    public function __construct()
    {
        // 
    }

    public function getOwnedPassengers(Request $request)
    {
        try {
            $loggedInUser = $this->guard()->user();

            $passengers = $loggedInUser->availablePassengers;
            return $this->jsonResponse("Success", ['passengers' => $passengers]);
        } catch (Exception $e) {
            return $this->jsonResponse($e->getMessage(), array(), $e->getCode());
        }
    }

    public function search(Request $request)
    {
        $validatedData = $request->validate([
            'passport_number' => 'nullable'
        ]);

        try {
            $query = Passenger::query();
            $query->where('passport_number', $request->passport_number);

            $passenger = $query->first();

            return $this->jsonResponse("Success", ['passenger' => $passenger]);
        } catch (Exception $e) {
            return $this->jsonResponse($e->getMessage(), array(), $e->getCode());
        }
    }

    public function store(Request $request)
    {
        $validatedData = $request->validate([
            'passport_number' => 'required',
            'name' => 'required|string|alpha_spaces',
            'nationality' => 'required|string',
            'gender' => 'required|in:0,1,2',
            'dob' => 'required|date_format:Y-m-d',
            'passport_expiry' => 'required|date_format:Y-m-d',
            'issuing_country' => 'required|string',
            'type' => 'required|in:0,1,2'
        ]);

        try {
            DB::beginTransaction();

            $passenger = $this->create($request->all(), $this->guard()->user());

            DB::commit();

            return $this->jsonResponse("Successfully created!", ['passenger' => $passenger]);
        } catch (Exception $e) {
            DB::rollBack();
            return $this->jsonResponse($e->getMessage(), array(), $e->getCode());
        }
    }

    protected function create($data = [], User $user)
    {
        if ($user) {
            return $user->passengers()->create($data);
        } else {
            return Passenger::create($data);
        }
    }

    /**
     * Get the guard to be used during authentication.
     *
     * @return \Illuminate\Contracts\Auth\StatefulGuard
     */
    protected function guard()
    {
        return Auth::guard('api-user');
    }
}

resources/views/admin/passenger/form.blade.php
@extends('templates.admin.master')

@section('title')
    {{ $passenger->id ? 'Edit' : 'Create'}} Passenger @parent
@endsection
@section('groupName', 'Passenger')

@section('content')
@if (!$passenger->id)
{!! Form::open(['route' => 'admin.passenger.store', 'method' => 'post', 'class' => 'form-horizontal']) !!}
@else
{!! Form::model($passenger, ['route' => ['admin.passenger.update', $passenger], 'method' => 'post', 'class' => 'form-horizontal']) !!}
@endif
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ $passenger->id ? 'Edit' : 'Create' }} Passenger</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <label for="passport_number" class="col-2 col-form-label">Passport Number</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('passport_number', old('passport_number'), array('class' => 'form-control', 'id' => 'passport_number', 'placeholder' => 'Passport Number')) }}
                        @if($errors->has('passport_number'))
                        <p class="status-text">{{ $errors->first('passport_number') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="name" class="col-2 col-form-label">Name</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::text('name', old('name'), array('class' => 'form-control', 'id' => 'name', 'placeholder' => 'Name')) }}
                        </div>
                        @if($errors->has('name'))
                        <p class="status-text">{{ $errors->first('name') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="nationality" class="col-2 col-form-label">Nationality</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::select('nationality', $nationalities, old('nationality'), array('class' => 'form-control', 'id' => 'nationality', 'placeholder' => 'Pick Nationality')) }}
                        </div>
                        @if($errors->has('nationality'))
                        <p class="status-text">{{ $errors->first('nationality') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="gender" class="col-2 col-form-label">Gender</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::select('gender', $genders, old('gender'), array('class' => 'form-control', 'id' => 'gender', 'placeholder' => 'Pick Gender')) }}
                        </div>
                        @if($errors->has('gender'))
                        <p class="status-text">{{ $errors->first('gender') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="dob" class="col-2 col-form-label">Date of Birth</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::text('dob', old('dob') ?? ($passenger->dob ? $passenger->dob->format('Y-m-d') : ''), array('class' => 'form-control', 'id' => 'dob', 'placeholder' => 'Ex: 1999-12-31')) }}
                        </div>
                        @if($errors->has('dob'))
                        <p class="status-text">{{ $errors->first('dob') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="issuing_country" class="col-2 col-form-label">Issuing Country</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::select('issuing_country', $issuingNationalities, old('issuing_country'), array('class' => 'form-control', 'id' => 'issuing_country', 'placeholder' => 'Pick Issuing Country')) }}
                        </div>
                        @if($errors->has('issuing_country'))
                        <p class="status-text">{{ $errors->first('issuing_country') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="passport_issue" class="col-2 col-form-label">Passport Issue</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::text('passport_issue', old('passport_issue') ?? ($passenger->passport_issue ? $passenger->passport_issue->format('Y-m-d') : ''), array('class' => 'form-control', 'id' => 'passport_issue', 'placeholder' => 'Ex: 1999-12-31')) }}
                        </div>
                        @if($errors->has('passport_issue'))
                        <p class="status-text">{{ $errors->first('passport_issue') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="passport_expiry" class="col-2 col-form-label">Passport Expiry</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::text('passport_expiry', old('passport_expiry') ?? ($passenger->passport_expiry ? $passenger->passport_expiry->format('Y-m-d') : ''), array('class' => 'form-control', 'id' => 'passport_expiry', 'placeholder' => 'Ex: 1999-12-31')) }}
                        </div>
                        @if($errors->has('passport_expiry'))
                        <p class="status-text">{{ $errors->first('passport_expiry') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="type" class="col-2 col-form-label">Age Type</label>
                <div class="col-10">
                    <div class="form-group">
                        <div id="wrapper">
                            {{ Form::select('type', $types, old('type'), array('class' => 'form-control', 'id' => 'type', 'placeholder' => 'Pick Age Type')) }}
                        </div>
                        @if($errors->has('type'))
                        <p class="status-text">{{ $errors->first('type') }}</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="text-center">
                <button type="submit" class="btn btn-round btn-info"><i class="fas fa-paper-plane"></i> Submit</button>
            </div>
        </div>
    </div>
{!! Form::close() !!}
@endsection

resources/views/admin/passenger/index.blade.php
@extends('templates.admin.master')
@extends('templates.datatables.datatables')

@section('title')
    Passenger List @parent
@endsection

@section('groupName', 'Passenger')

@section('content')
@include('templates.modal.modal-confirm')
<div class="card card-chart">
    <div class="card-header">
        <h4 class="card-title">Passenger List</h3>
        <div class="dropdown">
            <button type="button" class="btn btn-round btn-default dropdown-toggle btn-simple btn-icon no-caret" data-toggle="dropdown" aria-expanded="false">
                <i class="now-ui-icons loader_gear"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{{ route('admin.passenger.create') }}">Create new passenger</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered datatable dataTable" id="table" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Passport Number</th>
                    <th>Name</th>
                    <th>Nationality</th>
                    <th>Gender</th>
                    <th>Date of Birth</th>
                    <th>Issuing Country</th>
                    <th>Passport Issue</th>
                    <th>Passport Expiry</th>
                    <th>Type</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@endsection

@push('pageRelatedJs')
<script>
	$(document).ready(function(){
		var table = $('#table').DataTable(
		{
			processing: true,
			serverSide: true,
            responsive: true,
			ajax: {
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				url: '{!! route('admin.passenger.ajax') !!}',
				type: 'POST'
			},
			columns: [
                { data: 'id', name: 'id', className: 'text-center' },
                { data: 'passport_number', name: 'passport_number', className: 'text-center' },
                { data: 'name', name: 'name', className: 'text-center' },
                { data: 'nationality', name: 'nationality', className: 'text-center' },
                { data: 'gender', name: 'gender', className: 'text-center' },
                { data: 'dob', name: 'dob', className: 'text-center' },
                { data: 'issuing_country', name: 'issuing_country', className: 'text-center' },
                { data: 'passport_issue', name: 'passport_issue', className: 'text-center' },
                { data: 'passport_expiry', name: 'passport_expiry', className: 'text-center' },
                { data: 'type', name: 'type', className: 'text-center' },
                { data: 'action', name: 'action', className: 'text-center', sortable: false, searchable: false },
			]
		});
        $(table.table().container()).removeClass('form-inline');
	});
</script>
@endpush