routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Guest
	Route::group(['middleware' => 'guest:web-admin', 'guard' => 'web-admin'], function() {
		Route::get('login', 'AuthController@loginPage')->name('login.page');
		Route::post('login', 'AuthController@login')->name('login');
	});

	// Logged In
	Route::group(['middleware' => 'auth:web-admin', 'guard' => 'web-admin'], function() {
	    Route::post('logout', 'AuthController@logout')->name('logout');

    	Route::get('', 'DashboardController@index')->name('dashboard');
		
		// User
		Route::group(['namespace' => 'User', 'prefix' => 'users', 'as' => 'users.'], function() {
			Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
				// List
				Route::get('/', 'UserController@index')->name('index');
				Route::post('/', 'UserController@ajax')->name('ajax');
				
				Route::get('/new', 'UserController@edit')->name('create');
				Route::get('/{user}/edit', 'UserController@edit')->name('edit');
				Route::post('/store', 'UserController@update')->name('store');
				Route::post('/{user}/update', 'UserController@update')->name('update');
				Route::delete('/{user}/delete', 'UserController@delete')->name('delete');
				Route::get('/{user}/detail', 'UserController@detail')->name('detail');
			});
		});
		// Order
		Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
			Route::get('/', 'OrderController@index')->name('index');
			Route::post('/', 'OrderController@ajax')->name('ajax');
			Route::post('/export-excel', 'OrderController@exportExcel')->name('export-excel');
			Route::get('/{order}/detail', 'OrderController@detail')->name('detail');
			Route::get('/{order}/edit', 'OrderController@edit')->name('edit');
			Route::post('/{order}/update', 'OrderController@update')->name('update');
			Route::post('/{order}/cancel', 'OrderController@cancel')->name('cancel');
		});
		// Articles
		Route::group(['prefix' => 'article', 'as' => 'article.'], function() {
			Route::get('/', 'ArticleController@index')->name('index');
			Route::post('/', 'ArticleController@ajax')->name('ajax');
			Route::get('/new', 'ArticleController@edit')->name('create');
			Route::get('/{article}/edit', 'ArticleController@edit')->name('edit');
			Route::post('/store', 'ArticleController@update')->name('store');
			Route::post('/{article}/update', 'ArticleController@update')->name('update');
			Route::delete('/{article}/delete', 'ArticleController@delete')->name('delete');
		});
		// Comments
		Route::group(['prefix' => 'comment', 'as' => 'comment.'], function() {
			Route::get('/', 'CommentController@index')->name('index');
			Route::post('/', 'CommentController@ajax')->name('ajax');
			Route::get('/new', 'CommentController@edit')->name('create');
			Route::get('/{comment}/edit', 'CommentController@edit')->name('edit');
			Route::post('/store', 'CommentController@update')->name('store');
			Route::post('/{comment}/update', 'CommentController@update')->name('update');
			Route::delete('/{comment}/delete', 'CommentController@delete')->name('delete');
		});
		// Latest Promotion
		Route::group(['prefix' => 'latest-promotion', 'as' => 'latest-promotion.'], function() {
			Route::get('/', 'PromoController@index')->name('index');
			Route::post('/', 'PromoController@ajax')->name('ajax');
			Route::get('/new', 'PromoController@edit')->name('create');
			Route::get('/{promo}/edit', 'PromoController@edit')->name('edit');
			Route::post('/store', 'PromoController@update')->name('store');
			Route::post('/{promo}/update', 'PromoController@update')->name('update');
			Route::delete('/{promo}/delete', 'PromoController@delete')->name('delete');
		});
		// Config
		Route::group(['prefix' => 'config', 'as' => 'config.'], function() {
			Route::get('/', 'ConfigController@index')->name('index');
			Route::post('/', 'ConfigController@ajax')->name('ajax');
			Route::get('/new', 'ConfigController@edit')->name('create');
			Route::get('/{config}/edit', 'ConfigController@edit')->name('edit');
			Route::post('/store', 'ConfigController@update')->name('store');
			Route::post('/{config}/update', 'ConfigController@update')->name('update');
			Route::delete('/{config}/delete', 'ConfigController@delete')->name('delete');
		});
		// Passenger
		Route::group(['prefix' => 'passenger', 'as' => 'passenger.'], function() {
			Route::get('/', 'PassengerController@index')->name('index');
			Route::post('/', 'PassengerController@ajax')->name('ajax');
			Route::get('/new', 'PassengerController@edit')->name('create');
			Route::get('/{passenger}/edit', 'PassengerController@edit')->name('edit');
			Route::post('/store', 'PassengerController@update')->name('store');
			Route::post('/{passenger}/update', 'PassengerController@update')->name('update');
			Route::delete('/{passenger}/delete', 'PassengerController@delete')->name('delete');
		});
		// Preference
		Route::group(['namespace' => 'Preference', 'prefix' => 'preferences', 'as' => 'preferences.'], function() {
			// Faq
			Route::group(['prefix' => 'faq', 'as' => 'faq.'], function(){
				Route::get('/', 'FaqController@index')->name('index');
				Route::post('/list', 'FaqController@ajax')->name('ajax');
				Route::get('/new', 'FaqController@edit')->name('create');
				Route::post('/store', 'FaqController@update')->name('store');
				Route::get('/customize-urut', 'FaqController@customizeUrut')->name('customize-urut');
				Route::post('/update-urut', 'FaqController@updateUrut')->name('update-urut');
				Route::get('/{faq}/edit', 'FaqController@edit')->name('edit');
				Route::post('/{faq}/save', 'FaqController@update')->name('update');
				Route::delete('/{faq}/delete', 'FaqController@delete')->name('delete');
			});
		});
	});
});

Route::view('/batam-ferry-timing', 'batam-ferry-timing.index');
Route::get('/{any}', 'SpaController@index')->where('any', '.*');

app/Models/Article.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Helpers\Enums\ActiveStatus;
use App\Helpers\Enums\VerificationStatus;

class Article extends Model
{
    use SoftDeletes;
    
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'cover_id', 'publisher_id', 'tags', 'desc', 'intro', 'slug_url'
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [];
    protected $appends = ['cover_url', 'publisher_name'];

    protected $dates = [
        'deleted_at',
    ];

    public function publisher()
    {
        return $this->belongsTo('App\Models\Admin');
    }

    public function cover()
    {
        return $this->belongsTo('App\Models\Attachment');
    }

    public function comments()
    {
        return $this->hasMany('App\Models\Comment')->where('status', VerificationStatus::VERIFIED);
    }

    public function getCoverUrlAttribute($value)
    {
        return $this->cover ? $this->cover->url : '';
    }

    public function getPublisherNameAttribute($value)
    {
        return $this->publisher ? $this->publisher->fullname : 'No name';
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function scopeActive($query)
    {
        return $query->where('status', ActiveStatus::ACTIVE);
    }
}

app/Http/Controllers/Admin/ArticleController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Exception;
use Validator;
use App\Models\Article;
use Yajra\Datatables\Datatables;
use App\Helpers\Managers\ArticleManager;
use App\Helpers\Enums\ActiveStatus;

class ArticleController extends Controller
{
    public function index(Request $request)
    {
        $statusList = ActiveStatus::getArray();
        return view('admin.articles.index')
            ->with('statusList', $statusList);
    }

    public function edit(Request $request, Article $article)
    {
        $statusList = ActiveStatus::getArray();
        return view('admin.articles.form')
            ->with('article', $article)
            ->with('statusList', $statusList);
    }

    public function ajax(Request $request)
    {
    	$data = Article::with('publisher');
    	return Datatables::of($data)
            ->filter(function($model) use ($request) {
                if ($request->has('status_enum') && $request->status_enum !== null) {
                    $model->where('status', $request->status_enum);
                }
            }, true)
            ->addColumn('action', function ($model) {
                $str = '<div class="btn-group btn-group-circle">';
                $str .= '<a href='. route('admin.article.edit', ['article' => $model]) .' class="action"><span class="far fa-edit"></span></a>';
                $str .= '<a data-url="'. route('admin.article.delete', ['article' => $model]) .'" class="action" data-toggle="modal" data-target="#modalConfirm" data-table-name="#table"><span class="far fa-trash-alt"></span></a>';
                $str .= '</div>';
                return $str;
            })
            ->addColumn('cover', function ($model) {
                $str = $model->cover_url;
                return $str;
            })
            ->addColumn('status', function ($model) {
                return ActiveStatus::getString($model->status);
            })
            ->addColumn('tags', function ($model) {
                return $model->tags ? $model->tags : '' ;
            })
            ->escapeColumns([])
            ->make(true);
    }

    public function update(Request $request, Article $article)
    {
        $messageType = $article->id ? 'updated' : 'created';

        $rules = [
            'title' => 'required',
            'tags' => 'nullable',
            'intro' => 'nullable',
            'status' => 'required|integer',
            'desc' => 'nullable',
            'cover' => 'file',
        ];
        $validator = Validator::make($request->all(), $rules);
        $validator->sometimes('cover', 'required', function($data) use ($article) {
            return !$article->id;
        });
        $validator->validate();
        
        try {
            DB::beginTransaction();
            $articleManager = new ArticleManager($request->user());
            $updatedArticle = $articleManager->update($article, $request->all());

            DB::commit();
            return redirect()->route('admin.article.index')->with('success', 'Article successfully '.$messageType);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return redirect()->back()->withInput()->with('error', $errorMessage);
        }
    }

    public function delete(Request $request, Article $article)
    {
        try {
            DB::beginTransaction();
            $articleManager = new ArticleManager($request->user());
            $updatedArticle = $articleManager->delete($article);
            DB::commit();
            return response()->json(['message' => 'Article Deleted'], 200);
        } catch (Exception $e) {
            DB::rollBack();
            $errorMessage = $e->getMessage();
            return response()->json(['message' => $errorMessage], 500);
        }
    }
}

app/Http/Controllers/Api/V1/ArticleController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\ApiResponse;
use Exception;
use App\Models\Article;
use App\Models\Comment;
use App\Helpers\Managers\CommentManager;

class ArticleController extends Controller
{
    use ApiResponse;

    public function get(Request $request)
    {
        try {
            $articles = Article::active()->orderBy('created_at', 'desc')->paginate(6);
            return $this->jsonResponse("Success", ['articles' => $articles]);
        } catch (Exception $e) {
            return $this->jsonResponse($e->getMessage(), array(), $e->getCode());
        }
    }

    public function getArticleDetail(Request $request, Article $article)
    {
        $prevArticle = Article::where('id', '<', $article->id)->orderBy('id', 'desc')->select('title', 'slug')->first();
        $nextArticle = Article::where('id', '>', $article->id)->orderBy('id', 'asc')->select('title', 'slug')->first();
        return $this->jsonResponse("Success", ['article' => $article->load('comments'), 'prevArticle' => $prevArticle, 'nextArticle' => $nextArticle]);
    }

    public function getBatamHighlight(Request $request)
    {
        try {
            $articles = Article::active()->orderBy('created_at', 'desc')->take(6)->get();
            return $this->jsonResponse("Success", ['articles' => $articles]);
        } catch (Exception $e) {
            return $this->jsonResponse($e->getMessage(), array(), $e->getCode());
        }
    }

    public function postComment(Request $request, Article $article)
    {
        $validatedData = $request->validate([
            'desc' => 'required',
            'name' => 'required|string|alpha_spaces',
            'email' => 'required|email',
        ]);

        try {
            if (!$article) {
                throw new Exception('Article Not Found!', 404);
            }

            $commentManager = new CommentManager;
            $updatedComment = $commentManager->update(new Comment, $request->all(), $article);

            return $this->jsonResponse("Success");
        } catch (Exception $e) {
            return $this->jsonResponse($e->getMessage(), array(), $e->getCode());
        }
    }
}

resources/views/admin/articles/form.blade.php
@extends('templates.admin.master')

@section('title')
    {{ $article->id ? 'Edit' : 'Create'}} Article @parent
@endsection
@section('groupName', 'Articles')

@section('content')
@if (!$article->id)
{!! Form::open(['route' => 'admin.article.store', 'method' => 'post', 'files' => true, 'class' => 'form-horizontal']) !!}
@else
{!! Form::model($article, ['route' => ['admin.article.update', $article], 'method' => 'post', 'files' => true, 'class' => 'form-horizontal']) !!}
@endif
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ $article->id ? 'Edit' : 'Create' }} Article</h4>
        </div>
        <div class="card-body">
            <div class="row">
                <label for="title" class="col-2 col-form-label">Title</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('title', old('title'), array('class' => 'form-control', 'id' => 'title', 'placeholder' => 'Title', 'required')) }}
                        @if($errors->has('title'))
                        <p class="status-text">{{ $errors->first('title') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="tags" class="col-2 col-form-label">Tags</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('tags', old('tags'), array('class' => 'form-control v-hidden', 'id' => 'tags', 'placeholder' => 'Tags')) }}
                        @if($errors->has('tags'))
                        <p class="status-text">{{ $errors->first('tags') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="intro" class="col-2 col-form-label">Intro</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::textarea('intro', old('intro'), array('class' => 'form-control', 'id' => 'intro', 'placeholder' => 'Intro Text')) }}
                        @if($errors->has('intro'))
                        <p class="status-text">{{ $errors->first('intro') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="status" class="col-2 col-form-label">Status</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::select('status', $statusList, old('status'), array('class' => 'form-control', 'id' => 'status', 'placeholder' => 'Select Status')) }}
                        @if($errors->has('status'))
                        <p class="status-text">{{ $errors->first('status') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="desc" class="col-2 col-form-label">Description</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::textarea('desc', old('desc'), array('class' => 'form-control v-hidden', 'id' => 'desc', 'placeholder' => 'Description')) }}
                        @if($errors->has('desc'))
                        <p class="status-text">{{ $errors->first('desc') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-2 col-form-label">Cover</label>
                <div class="col-10">
                    <div class="form-group">
                        <div class="fileinput text-center fileinput-new d-inline-block" data-provides="fileinput">
                            <div class="fileinput-new thumbnail">
                                <img src="{{ $article->id && $article->cover_url ? $article->cover_url : asset('/assets/images/img-placeholder.png') }}">
                            </div>
                            <div class="fileinput-preview fileinput-exists thumbnail" style=""></div>
                            <div>
                                <span class="btn btn-primary btn-round btn-file">
                                    <span class="fileinput-new">Select image</span>
                                    <span class="fileinput-exists"><i class="fas fa-pencil-alt"></i> Change</span>
                                    {{ Form::file('cover') }}
                                </span>
                                <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fas fa-times-circle"></i> Remove</a>
                            </div>
                        </div>
                        @if($errors->has('cover'))
                        <p class="status-text">{{ $errors->first('cover') }}</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="text-center">
                <button type="submit" class="btn btn-round btn-info"><i class="fas fa-paper-plane"></i> Submit</button>
            </div>
        </div>
    </div>
{!! Form::close() !!}
@endsection

@push('pageRelatedCss')
<link rel="stylesheet" type="text/css" href="{{ asset('/css/jquery.tagsinput.min.css') }}"/>
@endpush

@push('pageRelatedJs')
<script src="{{ asset('/js/jasny-bootstrap.min.js') }}"></script>
<script src="{{ asset('/js/jquery.tagsinput.min.js') }}"></script>
<script src="{{ asset('/ckeditor/ckeditor.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $('#tags').tagsInput({
        'width': '100%',
        'defaultText': 'New Tag',
    });

    CKEDITOR.replace('desc', {
        height: 500
    });
});
</script>
@endpush

resources/views/admin/articles/index.blade.php
@extends('templates.admin.master')
@extends('templates.datatables.datatables')

@section('title')
    Article List @parent
@endsection
@section('groupName', 'Articles')

@section('content')
@include('templates.modal.modal-confirm')
<div class="card card-chart">
    <div class="card-header">
        <h4 class="card-title">Article List</h3>
        <div class="dropdown">
            <button type="button" class="btn btn-round btn-default dropdown-toggle btn-simple btn-icon no-caret" data-toggle="dropdown" aria-expanded="false">
                <i class="now-ui-icons loader_gear"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{{ route('admin.article.create') }}">Create new article</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-12 col-md-4">
                <div class="form-group">
                    <label for="filterStatus">Filter Status</label>
                    {{ Form::select('status', $statusList, '', ['class' => 'form-control nullable', 'id' => 'filterStatus', 'placeholder' => 'Show All Status']) }}
                </div>
            </div>
        </div>
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered datatable dataTable" id="table" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Title</th>
                    <th>Cover</th>
                    <th>Publisher</th>
                    <th class="d-none">Publisher First Name</th>
                    <th class="d-none">Publisher Last Name</th>
                    <th>Tags</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@endsection

@push('pageRelatedJs')
<script>
	$(document).ready(function(){
        var filterStatusEnum = null;

		var table = $('#table').DataTable(
		{
			processing: true,
			serverSide: true,
            responsive: true,
			ajax: {
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				url: '{!! route('admin.article.ajax') !!}',
                data: function(d) { 
                    d.status_enum = filterStatusEnum;
                },
				type: 'POST'
			},
			columns: [
                { data: 'id', name: 'id', className: 'text-center' },
                { data: 'title', name: 'title', className: 'text-center' },
                { data: 'cover', name: 'cover', className: 'text-center', sortable: false, searchable: false, render: function (data, type, full, meta) {
                    if (!data) return '';
                    var str = '<a href="'+ data +'" target="_blank"><img id="previewImage" src="'+ data +'"/></a>';
                    return str;
                    }
                },

                { data: 'publisher.fullname', className: 'text-center', sortable: false, searchable: false },
                { data: 'publisher.first_name', name: 'publisher.first_name', visible: false },
                { data: 'publisher.last_name', name: 'publisher.last_name', visible: false },

                { data: 'tags', name: 'tags', className: 'text-center', render: function(data){
                    return data.replace(/,/g, ',<br/>')
                }},
                { data: 'status', name: 'status', className: 'text-center', sortable: false, searchable: false},
                { data: 'action', name: 'action', className: 'text-center', sortable: false, searchable: false},
			]
		});
		$(table.table().container()).removeClass('form-inline');
        
        $('#filterStatus').on('change', function(e) { 
            filterStatusEnum = e.currentTarget.value; 
            table.draw(); 
        }); 
	});
</script>
@endpush