routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Admin
Route::group(['namespace' => 'Admin', 'prefix' => 'admin', 'as' => 'admin.'], function () {
    // Guest
	Route::group(['middleware' => 'guest:web-admin', 'guard' => 'web-admin'], function() {
		Route::get('login', 'AuthController@loginPage')->name('login.page');
		Route::post('login', 'AuthController@login')->name('login');
	});

	// Logged In
	Route::group(['middleware' => 'auth:web-admin', 'guard' => 'web-admin'], function() {
	    Route::post('logout', 'AuthController@logout')->name('logout');

    	Route::get('', 'DashboardController@index')->name('dashboard');
		
		// User
		Route::group(['namespace' => 'User', 'prefix' => 'users', 'as' => 'users.'], function() {
			Route::group(['prefix' => 'user', 'as' => 'user.'], function() {
				// List
				Route::get('/', 'UserController@index')->name('index');
				Route::post('/', 'UserController@ajax')->name('ajax');
				
				Route::get('/new', 'UserController@edit')->name('create');
				Route::get('/{user}/edit', 'UserController@edit')->name('edit');
				Route::post('/store', 'UserController@update')->name('store');
				Route::post('/{user}/update', 'UserController@update')->name('update');
				Route::delete('/{user}/delete', 'UserController@delete')->name('delete');
				Route::get('/{user}/detail', 'UserController@detail')->name('detail');
			});
		});
		// Order
		Route::group(['prefix' => 'order', 'as' => 'order.'], function() {
			Route::get('/', 'OrderController@index')->name('index');
			Route::post('/', 'OrderController@ajax')->name('ajax');
			Route::post('/export-excel', 'OrderController@exportExcel')->name('export-excel');
			Route::get('/{order}/detail', 'OrderController@detail')->name('detail');
			Route::get('/{order}/edit', 'OrderController@edit')->name('edit');
			Route::post('/{order}/update', 'OrderController@update')->name('update');
			Route::post('/{order}/cancel', 'OrderController@cancel')->name('cancel');
		});
		// Articles
		Route::group(['prefix' => 'article', 'as' => 'article.'], function() {
			Route::get('/', 'ArticleController@index')->name('index');
			Route::post('/', 'ArticleController@ajax')->name('ajax');
			Route::get('/new', 'ArticleController@edit')->name('create');
			Route::get('/{article}/edit', 'ArticleController@edit')->name('edit');
			Route::post('/store', 'ArticleController@update')->name('store');
			Route::post('/{article}/update', 'ArticleController@update')->name('update');
			Route::delete('/{article}/delete', 'ArticleController@delete')->name('delete');
		});
		// Comments
		Route::group(['prefix' => 'comment', 'as' => 'comment.'], function() {
			Route::get('/', 'CommentController@index')->name('index');
			Route::post('/', 'CommentController@ajax')->name('ajax');
			Route::get('/new', 'CommentController@edit')->name('create');
			Route::get('/{comment}/edit', 'CommentController@edit')->name('edit');
			Route::post('/store', 'CommentController@update')->name('store');
			Route::post('/{comment}/update', 'CommentController@update')->name('update');
			Route::delete('/{comment}/delete', 'CommentController@delete')->name('delete');
		});
		// Latest Promotion
		Route::group(['prefix' => 'latest-promotion', 'as' => 'latest-promotion.'], function() {
			Route::get('/', 'PromoController@index')->name('index');
			Route::post('/', 'PromoController@ajax')->name('ajax');
			Route::get('/new', 'PromoController@edit')->name('create');
			Route::get('/{promo}/edit', 'PromoController@edit')->name('edit');
			Route::post('/store', 'PromoController@update')->name('store');
			Route::post('/{promo}/update', 'PromoController@update')->name('update');
			Route::delete('/{promo}/delete', 'PromoController@delete')->name('delete');
		});
		// Config
		Route::group(['prefix' => 'config', 'as' => 'config.'], function() {
			Route::get('/', 'ConfigController@index')->name('index');
			Route::post('/', 'ConfigController@ajax')->name('ajax');
			Route::get('/new', 'ConfigController@edit')->name('create');
			Route::get('/{config}/edit', 'ConfigController@edit')->name('edit');
			Route::post('/store', 'ConfigController@update')->name('store');
			Route::post('/{config}/update', 'ConfigController@update')->name('update');
			Route::delete('/{config}/delete', 'ConfigController@delete')->name('delete');
		});
		// Passenger
		Route::group(['prefix' => 'passenger', 'as' => 'passenger.'], function() {
			Route::get('/', 'PassengerController@index')->name('index');
			Route::post('/', 'PassengerController@ajax')->name('ajax');
			Route::get('/new', 'PassengerController@edit')->name('create');
			Route::get('/{passenger}/edit', 'PassengerController@edit')->name('edit');
			Route::post('/store', 'PassengerController@update')->name('store');
			Route::post('/{passenger}/update', 'PassengerController@update')->name('update');
			Route::delete('/{passenger}/delete', 'PassengerController@delete')->name('delete');
		});
		// Preference
		Route::group(['namespace' => 'Preference', 'prefix' => 'preferences', 'as' => 'preferences.'], function() {
			// Faq
			Route::group(['prefix' => 'faq', 'as' => 'faq.'], function(){
				Route::get('/', 'FaqController@index')->name('index');
				Route::post('/list', 'FaqController@ajax')->name('ajax');
				Route::get('/new', 'FaqController@edit')->name('create');
				Route::post('/store', 'FaqController@update')->name('store');
				Route::get('/customize-urut', 'FaqController@customizeUrut')->name('customize-urut');
				Route::post('/update-urut', 'FaqController@updateUrut')->name('update-urut');
				Route::get('/{faq}/edit', 'FaqController@edit')->name('edit');
				Route::post('/{faq}/save', 'FaqController@update')->name('update');
				Route::delete('/{faq}/delete', 'FaqController@delete')->name('delete');
			});
		});
	});
});

Route::view('/batam-ferry-timing', 'batam-ferry-timing.index');
Route::get('/{any}', 'SpaController@index')->where('any', '.*');

app/Http/Controllers/Api/V1/LatestPromotionController.php
<?php

namespace App\Http\Controllers\Api\V1;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Traits\ApiResponse;
use Exception;
use App\Models\Promo;

class LatestPromotionController extends Controller
{
    use ApiResponse;
    
    public function get(Request $request)
    {
        try {
            $promos = Promo::active()->orderBy('created_at', 'desc')->get();
            return $this->jsonResponse("Success", ['promos' => $promos]);
        } catch (Exception $e) {
            return $this->jsonResponse($e->getMessage(), array(), $e->getCode());
        }
    }
}

resources/views/admin/latest-promotion/form.blade.php
@extends('templates.admin.master')

@section('title')
    {{ $promo->id ? 'Edit' : 'Create'}} Promo @parent
@endsection
@section('groupName', 'Latest Promotion')

@section('content')
@if (!$promo->id)
{!! Form::open(['route' => 'admin.latest-promotion.store', 'method' => 'post', 'files' => true, 'class' => 'form-horizontal']) !!}
@else
{!! Form::model($promo, ['route' => ['admin.latest-promotion.update', $promo], 'method' => 'post', 'files' => true, 'class' => 'form-horizontal']) !!}
@endif
    <div class="card">
        <div class="card-header">
            <h4 class="card-title">{{ $promo->id ? 'Edit' : 'Create' }} Promo</h3>
        </div>
        <div class="card-body">
            <div class="row">
                <label for="status" class="col-2 col-form-label">Status</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::select('status', $statusList, old('status'), array('class' => 'form-control', 'id' => 'status', 'placeholder' => 'Select Status')) }}
                        @if($errors->has('status'))
                        <p class="status-text">{{ $errors->first('status') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="startDate" class="col-2 col-form-label">Start Date</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('start_date', old('start_date'), array('class' => 'form-control datepickers', 'id' => 'startDate', 'placeholder' => 'Start Date')) }}
                        @if($errors->has('start_date'))
                        <p class="status-text">{{ $errors->first('start_date') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label for="endDate" class="col-2 col-form-label">End Date</label>
                <div class="col-10">
                    <div class="form-group">
                        {{ Form::text('end_date', old('end_date'), array('class' => 'form-control datepickers', 'id' => 'endDate', 'placeholder' => 'End Date')) }}
                        @if($errors->has('end_date'))
                        <p class="status-text">{{ $errors->first('end_date') }}</p>
                        @endif
                    </div>
                </div>
            </div>
            <div class="row">
                <label class="col-2 col-form-label">Cover</label>
                <div class="col-10">
                    <div class="form-group">
                        <div class="fileinput text-center fileinput-new d-inline-block" data-provides="fileinput">
                            <div class="fileinput-new thumbnail">
                                <img src="{{ $promo->id && $promo->cover_url ? $promo->cover_url : asset('/assets/images/img-placeholder.png') }}">
                            </div>
                            <div class="fileinput-preview fileinput-exists thumbnail" style=""></div>
                            <div>
                                <span class="btn btn-primary btn-round btn-file">
                                    <span class="fileinput-new">Select image</span>
                                    <span class="fileinput-exists"><i class="fas fa-pencil-alt"></i> Change</span>
                                    {{ Form::file('cover') }}
                                </span>
                                <a href="#pablo" class="btn btn-danger btn-round fileinput-exists" data-dismiss="fileinput"><i class="fas fa-times-circle"></i> Remove</a>
                            </div>
                        </div>
                        @if($errors->has('cover'))
                        <p class="status-text">{{ $errors->first('cover') }}</p>
                        @endif
                    </div>
                </div>
            </div>
        </div>
        <div class="card-footer">
            <div class="text-center">
                <button type="submit" class="btn btn-round btn-info"><i class="fas fa-paper-plane"></i> Submit</button>
            </div>
        </div>
    </div>
{!! Form::close() !!}
@endsection

@push('pageRelatedCss')
<link rel="stylesheet" type="text/css" href="{{ asset('css/bootstrap-datepicker.min.css') }}">
@endpush

@push('pageRelatedJs')
<script src="{{ asset('/js/jasny-bootstrap.min.js') }}"></script>
<script src="{{ asset('js/bootstrap-datepicker.min.js') }}"></script>
<script type="text/javascript">
$(document).ready(function(){
    var inputStart = $('input[name="start_date"]');
    var inputEnd = $('input[name="end_date"]');

    inputStart.datepicker({
        format: 'yyyy-mm-dd',
        autoclose: true,
        startDate: new Date(),
        todayHighlight: true
    });

    inputStart.on('change', function() {
        let val = inputStart.datepicker('getDates');
        let endVal = new Date(inputEnd.val());
        // let endVal = inputEnd.datepicker('getDates');

        if (val.length != 0) {
            if (endVal.length != 0 && val[0] > endVal) {
                inputEnd.val('');
            }

            inputEnd.datepicker('destroy');
            inputEnd.datepicker({
                format: 'yyyy-mm-dd',
                autoclose: true,
                todayHighlight: true,
                startDate: val[0]
            });

            inputEnd.prop('disabled', false);
        } else {
            inputEnd.prop('disabled', true);
        }
    });
});
</script>
@endpush

resources/views/admin/latest-promotion/index.blade.php
@extends('templates.admin.master')
@extends('templates.datatables.datatables')

@section('title')
    Promotion List @parent
@endsection

@section('groupName', 'Promotion')

@section('content')
@include('templates.modal.modal-confirm')
<div class="card card-chart">
    <div class="card-header">
        <h4 class="card-title">Promotion List</h3>
        <div class="dropdown">
            <button type="button" class="btn btn-round btn-default dropdown-toggle btn-simple btn-icon no-caret" data-toggle="dropdown" aria-expanded="false">
                <i class="now-ui-icons loader_gear"></i>
            </button>
            <div class="dropdown-menu dropdown-menu-right">
                <a class="dropdown-item" href="{{ route('admin.latest-promotion.create') }}">Create new promo</a>
            </div>
        </div>
    </div>
    <div class="card-body">
        <div class="row mb-3">
            <div class="col-12 col-md-4">
                <div class="form-group">
                    <label for="filterStatus">Filter Status</label>
                    {{ Form::select('status', $statusList, '', ['class' => 'form-control nullable', 'id' => 'filterStatus', 'placeholder' => 'Show All Status']) }}
                </div>
            </div>
        </div>
        <table cellpadding="0" cellspacing="0" class="table table-striped table-bordered datatable dataTable" id="table" width="100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Cover</th>
                    <th>Start / End Date</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody></tbody>
        </table>
    </div>
</div>
@endsection

@push('pageRelatedJs')
<script>
	$(document).ready(function(){
        var filterStatusEnum = null;

		var table = $('#table').DataTable(
		{
			processing: true,
			serverSide: true,
            responsive: true,
			ajax: {
				headers: {
					'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
				},
				url: '{!! route('admin.latest-promotion.ajax') !!}',
                data: function(d) { 
                    d.status_enum = filterStatusEnum;
                },
				type: 'POST'
			},
			columns: [
                { data: 'id', name: 'id', className: 'text-center' },
                { data: 'cover', name: 'cover', className: 'text-center', sortable: false, searchable: false, render: function (data, type, full, meta) {
                    if (!data) return '';
                    var str = '<a href="'+ data +'" target="_blank"><img id="previewImage" src="'+ data +'"/></a>';
                    return str;
                    }
                },
                { data: 'start_end_date', name: 'start_end_date', className: 'text-center', sortable: false, searchable: false },
                { data: 'status', name: 'status', sortable: false, searchable: false },
                { data: 'action', name: 'action', className: 'text-center', sortable: false },
			]
		});
        $(table.table().container()).removeClass('form-inline');
        
        $('#filterStatus').on('change', function(e) { 
            filterStatusEnum = e.currentTarget.value; 
            table.draw(); 
        }); 
	});
</script>
@endpush